# Generated by Django 5.0.3 on 2024-08-12 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post_field',
            new_name='post',
        ),
    ]
